-- ═══════════════════════════════════════════════════════════════════════
-- PILOT v1 — staging-baseline-core.sql  (STAGING فقط — Ref ngzaxzhoguxwbzyxlfkq)
-- ═══════════════════════════════════════════════════════════════════════
-- يبني الـSchema الأساسي للموديولات التسعة على Staging فارغ، مطابقًا لبنية
-- Production الفعلية (من preflight) + جداول الموديولات الفرعية (من ملفات
-- سكيما المستودع) + دوال هوية RLS + بيانات اختبار.
--
-- ⚠️ لا تشغّل هذا على Production — هو لتهيئة Staging الفارغ فقط.
-- آمن لإعادة التشغيل (كل الجداول IF NOT EXISTS). لا يحذف بيانات.
-- بعد نجاحه: شغّل pilot-01 مباشرة (دوال الهوية مضمّنة هنا).
-- ═══════════════════════════════════════════════════════════════════════

-- ─── (1) الأساس: أقسام / فروع / مستخدمون (مع كسر التبعية الدائرية) ─────
CREATE TABLE IF NOT EXISTS departments (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS branches (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       TEXT NOT NULL,
  address    TEXT,
  manager_id BIGINT,                    -- FK يُضاف بعد users
  is_active  BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS users (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name         TEXT NOT NULL,
  username          TEXT NOT NULL UNIQUE,
  password_plain    TEXT NOT NULL,
  email             TEXT UNIQUE,
  mobile_number     TEXT,
  role              TEXT NOT NULL,
  status            TEXT NOT NULL DEFAULT 'active',
  is_active         BOOLEAN DEFAULT TRUE,
  branch_id         BIGINT REFERENCES branches(id) ON DELETE SET NULL,
  department_id     BIGINT REFERENCES departments(id),
  direct_manager_id BIGINT REFERENCES users(id),
  auth_id           UUID UNIQUE,
  avatar_url        TEXT,
  nationality       TEXT,
  position_title    TEXT,
  joining_date      DATE,
  last_login_at     TIMESTAMPTZ,
  last_active_at    TIMESTAMPTZ,
  created_at        TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT users_role_check CHECK (role = ANY (ARRAY[
    'admin','company_manager','department_manager','projects_manager','development_manager',
    'meeting_organizer','branch_manager','deputy_manager','hr_manager','payroll_officer',
    'finance_manager','gl_accountant','ap_officer','ap_accountant','ar_officer',
    'operations_manager','maintenance_officer','quality_manager','procurement_manager',
    'delivery_manager','customer_service_manager','cc_manager','bi_analyst',
    'integrations_admin','franchise_manager','legal_officer','employee'])),
  CONSTRAINT users_status_check CHECK (status = ANY (ARRAY['active','inactive','suspended']))
);

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='branches_manager_id_fkey') THEN
    ALTER TABLE branches ADD CONSTRAINT branches_manager_id_fkey
      FOREIGN KEY (manager_id) REFERENCES users(id) ON DELETE SET NULL;
  END IF;
END $$;

-- ─── (2) الصلاحيات ─────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS role_permissions (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role        TEXT NOT NULL,
  section_key TEXT NOT NULL,
  can_view    BOOLEAN NOT NULL DEFAULT FALSE,
  can_manage  BOOLEAN NOT NULL DEFAULT FALSE,
  scope       TEXT NOT NULL DEFAULT 'company_wide',
  CONSTRAINT role_permissions_scope_check CHECK (scope = ANY (ARRAY['company_wide','own_department'])),
  CONSTRAINT role_permissions_role_section_key_key UNIQUE (role, section_key)
);
CREATE TABLE IF NOT EXISTS user_permission_overrides (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  section_key TEXT NOT NULL,
  can_view    BOOLEAN,
  can_manage  BOOLEAN,
  CONSTRAINT user_permission_overrides_user_id_section_key_key UNIQUE (user_id, section_key)
);

-- ─── (3) الاجتماعات ───────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS meetings (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title              TEXT NOT NULL,
  meeting_type       TEXT NOT NULL,
  meeting_datetime   TIMESTAMPTZ NOT NULL,
  location_type      TEXT NOT NULL,
  location_detail    TEXT,
  department_id      BIGINT REFERENCES departments(id),
  organizer_id       BIGINT REFERENCES users(id),
  status             TEXT NOT NULL DEFAULT 'scheduled',
  summary            TEXT,
  minutes_file_url   TEXT, minutes_file_name TEXT, minutes_notes TEXT,
  minutes_uploaded_at TIMESTAMPTZ,
  minutes_uploaded_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  created_at         TIMESTAMPTZ DEFAULT NOW(),
  updated_at         TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT meetings_status_check CHECK (status = ANY (ARRAY['scheduled','done','in_follow_up','closed','postponed','cancelled'])),
  CONSTRAINT meetings_location_type_check CHECK (location_type = ANY (ARRAY['in_person','online'])),
  CONSTRAINT meetings_meeting_type_check CHECK (meeting_type = ANY (ARRAY['weekly','emergency','administrative','financial','sales','operations']))
);
CREATE TABLE IF NOT EXISTS meeting_attendees (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  meeting_id BIGINT NOT NULL REFERENCES meetings(id) ON DELETE CASCADE,
  user_id BIGINT NOT NULL REFERENCES users(id),
  attendance_status TEXT NOT NULL DEFAULT 'invited',
  attendance_type TEXT DEFAULT 'in_person',
  CONSTRAINT meeting_attendees_meeting_id_user_id_key UNIQUE (meeting_id, user_id),
  CONSTRAINT meeting_attendees_attendance_status_check CHECK (attendance_status = ANY (ARRAY['invited','attended','absent'])),
  CONSTRAINT meeting_attendees_attendance_type_check CHECK (attendance_type = ANY (ARRAY['in_person','remote']))
);
CREATE TABLE IF NOT EXISTS meeting_minutes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  meeting_id BIGINT NOT NULL REFERENCES meetings(id) ON DELETE CASCADE,
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS meeting_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  meeting_id BIGINT REFERENCES meetings(id),
  requester_id BIGINT NOT NULL REFERENCES users(id),
  invitee_id BIGINT NOT NULL REFERENCES users(id),
  proposed_datetime TIMESTAMPTZ NOT NULL,
  location_type TEXT NOT NULL DEFAULT 'in_person',
  location_detail TEXT, reason TEXT, responded_at TIMESTAMPTZ,
  status TEXT NOT NULL DEFAULT 'pending',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT meeting_requests_status_check CHECK (status = ANY (ARRAY['pending','accepted','declined'])),
  CONSTRAINT meeting_requests_location_type_check CHECK (location_type = ANY (ARRAY['in_person','online']))
);

-- ─── (4) المهام ───────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS action_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  assigned_to BIGINT REFERENCES users(id),
  meeting_id BIGINT REFERENCES meetings(id) ON DELETE CASCADE,
  decision_id BIGINT,   -- FK يُضاف بعد decisions
  department_id BIGINT REFERENCES departments(id),
  due_date DATE, start_date DATE, duration_days INTEGER,
  priority TEXT NOT NULL DEFAULT 'medium',
  status TEXT NOT NULL DEFAULT 'not_started',
  progress_percent INTEGER DEFAULT 0,
  follow_up_notes TEXT, delay_reason TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT action_items_status_check CHECK (status = ANY (ARRAY['not_started','in_progress','completed','delayed'])),
  CONSTRAINT action_items_priority_check CHECK (priority = ANY (ARRAY['high','medium','low']))
);
CREATE TABLE IF NOT EXISTS department_tasks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL, description TEXT,
  assigned_by BIGINT NOT NULL REFERENCES users(id),
  assigned_to BIGINT NOT NULL REFERENCES users(id),
  department_id BIGINT REFERENCES departments(id),
  due_datetime TIMESTAMPTZ,
  priority TEXT NOT NULL DEFAULT 'medium',
  status TEXT NOT NULL DEFAULT 'not_started',
  progress_percent INTEGER NOT NULL DEFAULT 0,
  attachment_url TEXT, attachment_name TEXT, attachment_type TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT department_tasks_status_check CHECK (status = ANY (ARRAY['not_started','in_progress','completed','delayed'])),
  CONSTRAINT department_tasks_priority_check CHECK (priority = ANY (ARRAY['high','medium','low']))
);

-- ─── (5) القرارات ─────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS decisions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  decision_text TEXT NOT NULL,
  meeting_id BIGINT REFERENCES meetings(id) ON DELETE CASCADE,
  department_id BIGINT REFERENCES departments(id),
  responsible_user_id BIGINT REFERENCES users(id),
  due_date DATE, notes TEXT,
  priority TEXT NOT NULL DEFAULT 'medium',
  status TEXT NOT NULL DEFAULT 'new',
  created_by BIGINT REFERENCES users(id),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT decisions_priority_check CHECK (priority = ANY (ARRAY['high','medium','low'])),
  CONSTRAINT decisions_status_check CHECK (status = ANY (ARRAY['new','in_progress','executed','delayed','cancelled','pending_approval']))
);
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='action_items_decision_id_fkey') THEN
    ALTER TABLE action_items ADD CONSTRAINT action_items_decision_id_fkey
      FOREIGN KEY (decision_id) REFERENCES decisions(id);
  END IF;
END $$;
CREATE TABLE IF NOT EXISTS decision_sub_responsibles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  decision_id BIGINT NOT NULL REFERENCES decisions(id) ON DELETE CASCADE,
  user_id BIGINT NOT NULL REFERENCES users(id),
  CONSTRAINT decision_sub_responsibles_decision_id_user_id_key UNIQUE (decision_id, user_id));
CREATE TABLE IF NOT EXISTS decision_viewers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  decision_id BIGINT NOT NULL REFERENCES decisions(id) ON DELETE CASCADE,
  user_id BIGINT NOT NULL REFERENCES users(id),
  CONSTRAINT decision_viewers_decision_id_user_id_key UNIQUE (decision_id, user_id));
CREATE TABLE IF NOT EXISTS decision_activity_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  decision_id BIGINT NOT NULL REFERENCES decisions(id) ON DELETE CASCADE,
  action_text TEXT NOT NULL,
  created_by BIGINT REFERENCES users(id),
  created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS decision_acknowledgments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  decision_id BIGINT NOT NULL REFERENCES decisions(id) ON DELETE CASCADE,
  user_id BIGINT NOT NULL REFERENCES users(id),
  acknowledged_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT decision_acknowledgments_decision_id_user_id_key UNIQUE (decision_id, user_id));

-- ─── (6) الطوارئ ──────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS emergency_alerts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT, message TEXT NOT NULL,
  emergency_type TEXT DEFAULT 'operations',
  severity TEXT NOT NULL DEFAULT 'medium',
  location TEXT,
  department_id BIGINT REFERENCES departments(id),
  sender_id BIGINT NOT NULL REFERENCES users(id),
  recipient_id BIGINT REFERENCES users(id),
  status TEXT NOT NULL DEFAULT 'open',
  processing_status TEXT NOT NULL DEFAULT 'new',
  requires_ack BOOLEAN NOT NULL DEFAULT TRUE,
  is_draft BOOLEAN NOT NULL DEFAULT FALSE,
  escalation_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  escalation_after_minutes INTEGER DEFAULT 15,
  escalation_to TEXT DEFAULT 'company_manager',
  attachment_url TEXT, attachment_name TEXT,
  resolved_at TIMESTAMPTZ, resolved_by BIGINT REFERENCES users(id),
  closed_at TIMESTAMPTZ, closed_by BIGINT REFERENCES users(id),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT emergency_alerts_processing_status_check CHECK (processing_status = ANY (ARRAY['new','in_progress','closed'])),
  CONSTRAINT emergency_alerts_status_check CHECK (status = ANY (ARRAY['open','resolved'])),
  CONSTRAINT emergency_alerts_severity_check CHECK (severity = ANY (ARRAY['low','medium','high','critical']))
);
CREATE TABLE IF NOT EXISTS emergency_recipients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  alert_id BIGINT NOT NULL REFERENCES emergency_alerts(id) ON DELETE CASCADE,
  user_id BIGINT NOT NULL REFERENCES users(id),
  is_cc BOOLEAN NOT NULL DEFAULT FALSE,
  acknowledged_at TIMESTAMPTZ,
  CONSTRAINT emergency_recipients_alert_id_user_id_key UNIQUE (alert_id, user_id));
CREATE TABLE IF NOT EXISTS emergency_activity_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  alert_id BIGINT NOT NULL REFERENCES emergency_alerts(id) ON DELETE CASCADE,
  action_text TEXT NOT NULL,
  created_by BIGINT REFERENCES users(id),
  created_at TIMESTAMPTZ DEFAULT NOW());

-- ─── (7) الصيانة (الأساس من preflight + الفرعية من سكيما المستودع) ─────
CREATE TABLE IF NOT EXISTS maintenance_suppliers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL, activity TEXT, phone TEXT, email TEXT, notes TEXT,
  rating NUMERIC DEFAULT 0, works_count INTEGER DEFAULT 0,
  is_active BOOLEAN DEFAULT TRUE, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS maintenance_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_no TEXT UNIQUE,
  branch_id BIGINT REFERENCES branches(id) ON DELETE SET NULL,
  affected_area TEXT, maintenance_type TEXT, issue_title TEXT, branch_location TEXT,
  description TEXT, cause TEXT, severity TEXT DEFAULT 'normal',
  affects_operation BOOLEAN DEFAULT FALSE, impact_on_operation TEXT DEFAULT 'none',
  stoppage_type TEXT, additional_notes TEXT, internal_notes TEXT,
  attachment_url TEXT, video_url TEXT, is_draft BOOLEAN DEFAULT FALSE,
  status TEXT DEFAULT 'new',
  requester_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  current_owner_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  reported_at TIMESTAMPTZ DEFAULT NOW(), reject_reason TEXT,
  estimated_cost NUMERIC, final_cost NUMERIC, selected_quote_id BIGINT,
  created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS maintenance_inspections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id BIGINT REFERENCES maintenance_requests(id) ON DELETE CASCADE,
  cause TEXT, fix_type TEXT, estimated_cost NUMERIC, needs_spare_parts BOOLEAN DEFAULT FALSE,
  spare_parts_details TEXT, recommendation TEXT, notes TEXT,
  inspector_id BIGINT REFERENCES users(id) ON DELETE SET NULL, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS maintenance_quotes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id BIGINT REFERENCES maintenance_requests(id) ON DELETE CASCADE,
  supplier_id BIGINT REFERENCES maintenance_suppliers(id) ON DELETE SET NULL,
  supplier_name TEXT, price NUMERIC, duration_days INT, warranty_months INT,
  spare_parts_details TEXT, notes TEXT, attachment_url TEXT,
  is_selected BOOLEAN DEFAULT FALSE, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS maintenance_finance_approvals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id BIGINT REFERENCES maintenance_requests(id) ON DELETE CASCADE,
  approved BOOLEAN, approved_amount NUMERIC, payment_method TEXT, po_number TEXT,
  reject_reason TEXT, approver_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS maintenance_repairs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id BIGINT REFERENCES maintenance_requests(id) ON DELETE CASCADE,
  technician_name TEXT, supplier_id BIGINT REFERENCES maintenance_suppliers(id) ON DELETE SET NULL,
  started_at TIMESTAMPTZ, ended_at TIMESTAMPTZ, branch_partially_closed BOOLEAN DEFAULT FALSE,
  execution_notes TEXT, what_was_fixed TEXT, final_cost NUMERIC, spare_parts_used TEXT,
  before_photos_url TEXT, after_photos_url TEXT, warranty_details TEXT, technician_notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS maintenance_receipts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id BIGINT REFERENCES maintenance_requests(id) ON DELETE CASCADE,
  closure_status TEXT, confirmer_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  notes TEXT, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS maintenance_attachments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id BIGINT REFERENCES maintenance_requests(id) ON DELETE CASCADE,
  stage TEXT, file_url TEXT, file_name TEXT, file_type TEXT,
  uploaded_by BIGINT REFERENCES users(id) ON DELETE SET NULL, uploaded_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS maintenance_timeline (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id BIGINT REFERENCES maintenance_requests(id) ON DELETE CASCADE,
  event_type TEXT, from_status TEXT, to_status TEXT, note TEXT,
  actor_id BIGINT REFERENCES users(id) ON DELETE SET NULL, created_at TIMESTAMPTZ DEFAULT NOW());

-- ─── (8) الجودة ───────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS quality_sections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL, sort_order INT DEFAULT 0, corrective_options TEXT[] DEFAULT '{}',
  is_active BOOLEAN DEFAULT TRUE, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS quality_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  section_id BIGINT REFERENCES quality_sections(id) ON DELETE CASCADE,
  text TEXT NOT NULL, sort_order INT DEFAULT 0, is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS quality_visits (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  visit_no TEXT UNIQUE,
  branch_id BIGINT REFERENCES branches(id) ON DELETE SET NULL,
  inspector_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  inspector_name TEXT, visit_type TEXT DEFAULT 'daily', visit_date DATE DEFAULT CURRENT_DATE,
  started_at TIMESTAMPTZ, ended_at TIMESTAMPTZ, status TEXT DEFAULT 'draft',
  total_items INT DEFAULT 0, conform_count INT DEFAULT 0, follow_up_count INT DEFAULT 0,
  non_conform_count INT DEFAULT 0, na_count INT DEFAULT 0, compliance_pct NUMERIC DEFAULT 0,
  notes TEXT, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS quality_visit_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  visit_id BIGINT REFERENCES quality_visits(id) ON DELETE CASCADE,
  section_id BIGINT, item_id BIGINT, item_text TEXT, status TEXT,
  corrective_action TEXT, custom_corrective_action TEXT, notes TEXT,
  responsible_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  responsible_role TEXT, due_date DATE, action_status TEXT, severity TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS quality_visit_sections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  visit_id BIGINT REFERENCES quality_visits(id) ON DELETE CASCADE,
  section_id BIGINT, section_title TEXT, corrective_actions TEXT, severity TEXT,
  execution_status TEXT, notes TEXT, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS quality_attachments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  visit_id BIGINT REFERENCES quality_visits(id) ON DELETE CASCADE,
  section_id BIGINT, file_url TEXT, file_name TEXT, file_type TEXT,
  uploaded_by BIGINT REFERENCES users(id) ON DELETE SET NULL, uploaded_at TIMESTAMPTZ DEFAULT NOW());

-- ─── (9) التوصيل ──────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS delivery_companies (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL, is_active BOOLEAN NOT NULL DEFAULT TRUE,
  sort_order INTEGER NOT NULL DEFAULT 100, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS branch_delivery_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  branch_id BIGINT REFERENCES branches(id) ON DELETE SET NULL,
  company_id BIGINT REFERENCES delivery_companies(id) ON DELETE SET NULL,
  company_name TEXT, order_ref TEXT, amount NUMERIC, notes TEXT,
  invoice_photo_url TEXT NOT NULL, order_photo1_url TEXT, order_photo2_url TEXT,
  created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());

-- ─── (10) دوال هوية RLS (بعد وجود users) ──────────────────────────────
CREATE OR REPLACE FUNCTION current_app_user_id()
RETURNS BIGINT LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT id FROM users WHERE auth_id = auth.uid(); $$;
CREATE OR REPLACE FUNCTION current_app_role()
RETURNS TEXT LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT role FROM users WHERE auth_id = auth.uid(); $$;
GRANT EXECUTE ON FUNCTION current_app_user_id() TO authenticated, anon;
GRANT EXECUTE ON FUNCTION current_app_role() TO authenticated, anon;

-- ─── (11) بيانات اختبار (فرعان، قسمان، 5 مستخدمين) ────────────────────
INSERT INTO departments (id, name) VALUES (1,'التشغيل'),(2,'المالية')
  ON CONFLICT (id) DO NOTHING;
INSERT INTO branches (id, name) VALUES (1,'فرع أ'),(2,'فرع ب')
  ON CONFLICT (id) DO NOTHING;
INSERT INTO users (id, full_name, username, password_plain, email, role, status, is_active, branch_id, department_id) VALUES
  (1,'مدير النظام','admin_test','Test12345','admin@stg.local','admin','active',TRUE,NULL,NULL),
  (2,'مدير فرع أ','bm1_test','Test12345','bm1@stg.local','branch_manager','active',TRUE,1,1),
  (3,'موظف فرع أ','emp1_test','Test12345','emp1@stg.local','employee','active',TRUE,1,1),
  (4,'مدير فرع ب','bm2_test','Test12345','bm2@stg.local','branch_manager','active',TRUE,2,2),
  (5,'مدير قسم التشغيل','dm_test','Test12345','dm@stg.local','department_manager','active',TRUE,1,1)
  ON CONFLICT (id) DO NOTHING;
-- ضبط تسلسل الهوية بعد الإدراج اليدوي للمعرّفات
SELECT setval(pg_get_serial_sequence('departments','id'), GREATEST((SELECT MAX(id) FROM departments),1));
SELECT setval(pg_get_serial_sequence('branches','id'),    GREATEST((SELECT MAX(id) FROM branches),1));
SELECT setval(pg_get_serial_sequence('users','id'),       GREATEST((SELECT MAX(id) FROM users),1));

-- ═══ تأكيد ═══
SELECT 'tables' AS what, count(*)::text AS n FROM information_schema.tables
  WHERE table_schema='public' AND table_name IN (
    'users','branches','departments','role_permissions','user_permission_overrides',
    'meetings','meeting_attendees','meeting_minutes','meeting_requests',
    'action_items','department_tasks','decisions','decision_sub_responsibles',
    'decision_viewers','decision_activity_log','decision_acknowledgments',
    'emergency_alerts','emergency_recipients','emergency_activity_log',
    'maintenance_requests','maintenance_suppliers','maintenance_inspections','maintenance_quotes',
    'maintenance_finance_approvals','maintenance_repairs','maintenance_receipts',
    'maintenance_attachments','maintenance_timeline',
    'quality_sections','quality_items','quality_visits','quality_visit_items',
    'quality_visit_sections','quality_attachments',
    'delivery_companies','branch_delivery_requests')
UNION ALL SELECT 'test_users', count(*)::text FROM users
UNION ALL SELECT 'helpers', count(*)::text FROM pg_proc
  WHERE proname IN ('current_app_user_id','current_app_role');
